### ISSUE TITLE
ProtoSpace挙動確認

### ISSUE THREAD

**Issue by masarusiro** [masarusiro/protospace-38918#5]
ProtoSpaceのURL
https://protospace-38918.onrender.com/

**Comment by masarusiro** [comment]
間違えて違うところにissueを作っていたので新しく作りました。
前回のissue
https://github.com/masarusiro/training_curriculum/issues/11


[修正依頼箇所]

## ログイン・ログアウトの状態に関わらず、一覧表示されている画像およびプロトタイプ名をクリックすると、該当するプロトタイプの詳細ページへ遷移すること
プロトタイプ画像から詳細ページへの遷移はできますが、プロトタイプ名をクリックしても詳細ページに遷移できません。
修正をお願いします。

 ##正しく編集できた場合は、詳細ページへ遷移すること
編集後にトップページに遷移してしまうため、詳細ページに遷移先を変更お願いします。

## ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること
ユーザー名をクリックした際の遷移先が全てログインユーザーになっています。
クリックするユーザー名ごとに、対象のユーザー詳細ページに遷移できるように修正をお願いします。

 ##ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること
一部ユーザー名が正しく表示されていないため、修正をお願いします。

## ログアウト状態のユーザーであっても、トップページ・プロトタイプ詳細ページ・ユーザー詳細ページ・ユーザー新規登録ページ・ログインページには遷移できること
ログアウト状態でプロトタイプ詳細ページに遷移しようとするとエラーになってしまいます。

**Comment by masarusiro** [comment]
修正しました。確認お願いします

**Comment by motomuun** [comment]
@masarusiro さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
